LootJS.modifiers(event => {
    const materials = ['stone', 'iron', 'diamond', 'netherite'] // hammer materials.
    materials.forEach(m => {    // for each tier of hammer...
        // cobblestone drops gravel when broken by a hammer.
        event.addBlockModifier("minecraft:cobblestone")  // when breaking cobblestone...
            .matchTool(`kubejs:${m}_hammer`)   // ...and when the player is using the stone hammer...
            .removeLoot("minecraft:cobblestone")    // ...remove the cobblestone drop...
            .addLoot(LootEntry.of("minecraft:gravel"))  // ...and replace it with gravel.
        // gravel drops sand when broken by a hammer.
        event.addBlockModifier("minecraft:gravel")   // when breaking gravel...
            .matchTool(`kubejs:${m}_hammer`)   // ...and when the player is using the stone hammer...
            .removeLoot("minecraft:gravel") // ...remove the gravel drop...
            .addLoot(LootEntry.of("minecraft:sand"))    // ...and replace it with sand.
        // tuff drops tuff gravel when broken by a hammer.
        event.addBlockModifier("minecraft:tuff") // when breaking tuff...
            .matchTool(`kubejs:${m}_hammer`)   // ...and when the player is using the stone hammer...
            .removeLoot("minecraft:tuff")   // ...remove the tuff drop...
            .addLoot(LootEntry.of("kubejs:tuff_gravel"))    // ...and replace it with tuff gravel.
        // cobbled deepslate drops deepslate gravel when broken by a hammer.
        event.addBlockModifier("minecraft:cobbled_deepslate")    // when breaking cobbled deepslate...
            .matchTool(`kubejs:${m}_hammer`)   // ...and when the player is using the stone hammer...
            .removeLoot("minecraft:cobbled_deepslate")  // ...remove the cobbled deepslate drop...
            .addLoot(LootEntry.of("kubejs:deepslate_gravel"))   // ...and replace it with deepslate gravel.
        event.addBlockModifier("minecraft:granite")
            .matchTool(`kubejs:${m}_hammer`)
            .removeLoot("minecraft:granite")
            .addLoot(LootEntry.of("kubejs:granite_gravel"))
        event.addBlockModifier("minecraft:diorite")
            .matchTool(`kubejs:${m}_hammer`)
            .removeLoot("minecraft:diorite")
            .addLoot(LootEntry.of("kubejs:diorite_gravel"))
        event.addBlockModifier("minecraft:andesite")
            .matchTool(`kubejs:${m}_hammer`)
            .removeLoot("minecraft:andesite")
            .addLoot(LootEntry.of("kubejs:andesite_gravel"))
    })
})